import 'package:uuid/uuid.dart';

class RopaDeportiva {
  final String id;
  final String imagen;
  final String titulo;
  final String descripcion;
  final double precio;
  final List<String> tallas;
  final bool enOferta;
  final int ponderacion;

  RopaDeportiva({
    required this.id,
    required this.imagen,
    required this.titulo,
    required this.descripcion,
    required this.precio,
    required this.tallas,
    required this.enOferta,
    required this.ponderacion,
  });
}

final List<RopaDeportiva> ropaDeportivaFemenina = [
  // RopaDeportiva(
  //   id: Uuid().v4(),
  //   imagen: 'assets/tops/top1.jpg',
  //   titulo: 'Leggings Deportivos',
  //   descripcion: 'Leggings de alta elasticidad para máximo confort.',
  //   precio: 29.99,
  //   tallas: ['S', 'M', 'L', 'XL'],
  //   enOferta: true,
  //   ponderacion: 5,
  // ),
  RopaDeportiva(
    id: Uuid().v4(),
    imagen: 'assets/tops/top1.jpg',
    titulo: 'Top Deportivo',
    descripcion: 'Top de soporte medio para entrenamientos intensos.',
    precio: 24.99,
    tallas: ['XS', 'S', 'M', 'L'],
    enOferta: false,
    ponderacion: 4,
  ),
  RopaDeportiva(
    id: Uuid().v4(),
    imagen: 'assets/tops/top2.jpg',
    titulo: 'Camiseta Running',
    descripcion: 'Camiseta transpirable para correr con comodidad.',
    precio: 19.99,
    tallas: ['S', 'M', 'L'],
    enOferta: true,
    ponderacion: 3,
  ),
  RopaDeportiva(
    id: Uuid().v4(),
    imagen: 'assets/tops/top3.jpg',
    titulo: 'Top Deportivo',
    descripcion: 'Top de soporte para entrenamientos bajo impacto.',
    precio: 22.99,
    tallas: ['M', 'L', 'XL'],
    enOferta: false,
    ponderacion: 4,
  ),
  RopaDeportiva(
    id: Uuid().v4(),
    imagen: 'assets/tops/top4.jpg',
    titulo: 'Top Deportivo',
    descripcion: 'Top de soporte para entrenamientos alto impacto.',
    precio: 39.99,
    tallas: ['S', 'M', 'L', 'XL'],
    enOferta: true,
    ponderacion: 5,
  ),
  RopaDeportiva(
    id: Uuid().v4(),
    imagen: 'assets/tops/top5.jpg',
    titulo: 'Top Deportivo',
    descripcion: 'Top de soporte alto para entrenamientos intensos.',
    precio: 34.99,
    tallas: ['XS', 'S', 'M', 'L'],
    enOferta: false,
    ponderacion: 4,
  ),
  RopaDeportiva(
    id: Uuid().v4(),
    imagen: 'assets/tops/top6.jpg',
    titulo: 'Top Deportivo',
    descripcion: 'Top de soporte bajo para entrenamientos intensos.',
    precio: 27.99,
    tallas: ['S', 'M', 'L'],
    enOferta: true,
    ponderacion: 5,
  ),
  RopaDeportiva(
    id: Uuid().v4(),
    imagen: 'assets/tops/top7.jpg',
    titulo: 'Top Deportivo',
    descripcion: 'Top de soporte bajo para entrenamientos intensos.',
    precio: 32.99,
    tallas: ['M', 'L', 'XL', 'XXL'],
    enOferta: false,
    ponderacion: 3,
  ),
  RopaDeportiva(
    id: Uuid().v4(),
    imagen: 'assets/tops/top8.jpg',
    titulo: 'Top Deportivo',
    descripcion: 'Top de soporte medio para entrenamientos intensos.',
    precio: 26.99,
    tallas: ['S', 'M', 'L'],
    enOferta: true,
    ponderacion: 4,
  ),
  RopaDeportiva(
    id: Uuid().v4(),
    imagen: 'assets/tops/top9.jpg',
    titulo: 'Top Deportivo',
    descripcion: 'Top de soporte para entrenamientos bajo impacto.',
    precio: 28.99,
    tallas: ['XS', 'S', 'M'],
    enOferta: false,
    ponderacion: 4,
  ),
  RopaDeportiva(
    id: Uuid().v4(),
    imagen: 'assets/tops/top10.jpg',
    titulo: 'Top Deportivo',
    descripcion: 'Top de soporte para entrenamientos medio impacto.',
    precio: 36.99,
    tallas: ['S', 'M', 'L', 'XL'],
    enOferta: true,
    ponderacion: 5,
  ),
  RopaDeportiva(
    id: Uuid().v4(),
    imagen: 'assets/tops/top11.jpg',
    titulo: 'Top Deportivo',
    descripcion: 'Camiseta transpirable para dias frescos.',
    precio: 42.99,
    tallas: ['M', 'L', 'XL'],
    enOferta: false,
    ponderacion: 3,
  ),
  RopaDeportiva(
    id: Uuid().v4(),
    imagen: 'assets/tops/top12.jpg',
    titulo: 'Top Deportivo',
    descripcion: 'Top de soporte para entrenamientos medio impacto.',
    precio: 25.99,
    tallas: ['S', 'M', 'L'],
    enOferta: true,
    ponderacion: 4,
  ),
  RopaDeportiva(
    id: Uuid().v4(),
    imagen: 'assets/tops/top13.jpg',
    titulo: 'Top Deportivo',
    descripcion: 'Camiseta transpirable para dias frescos.',
    precio: 31.99,
    tallas: ['M', 'L', 'XL'],
    enOferta: false,
    ponderacion: 4,
  ),
  // RopaDeportiva(
  //   id: Uuid().v4(),
  //   imagen: 'assets/images/chaleco_running.jpg',
  //   titulo: 'Chaleco Running',
  //   descripcion:
  //       'Chaleco ligero y reflectante para correr en condiciones de poca luz.',
  //   precio: 38.99,
  //   tallas: ['S', 'M', 'L'],
  //   enOferta: true,
  //   ponderacion: 5,
  // ),
  // RopaDeportiva(
  //   id: Uuid().v4(),
  //   imagen: 'assets/images/mallas_ciclista.jpg',
  //   titulo: 'Mallas de Ciclista',
  //   descripcion: 'Mallas acolchadas para ciclismo de larga distancia.',
  //   precio: 45.99,
  //   tallas: ['S', 'M', 'L', 'XL'],
  //   enOferta: false,
  //   ponderacion: 3,
  // ),
  // RopaDeportiva(
  //   id: Uuid().v4(),
  //   imagen: 'assets/images/camiseta_entrenamiento.jpg',
  //   titulo: 'Camiseta de Entrenamiento',
  //   descripcion:
  //       'Camiseta transpirable y de secado rápido para todo tipo de entrenamientos.',
  //   precio: 23.99,
  //   tallas: ['S', 'M', 'L'],
  //   enOferta: true,
  //   ponderacion: 4,
  // ),
  // RopaDeportiva(
  //   id: Uuid().v4(),
  //   imagen: 'assets/images/top_natacion.jpg',
  //   titulo: 'Top de Natación',
  //   descripcion: 'Top resistente al cloro y de secado rápido para natación.',
  //   precio: 25.99,
  //   tallas: ['S', 'M', 'L'],
  //   enOferta: true,
  //   ponderacion: 4,
  // ),
  // RopaDeportiva(
  //   id: Uuid().v4(),
  //   imagen: 'assets/images/pantalones_cortos_senderismo.jpg',
  //   titulo: 'Pantalones Cortos Senderismo',
  //   descripcion:
  //       'Pantalones cortos resistentes y ligeros para senderismo y trekking.',
  //   precio: 31.99,
  //   tallas: ['M', 'L', 'XL'],
  //   enOferta: false,
  //   ponderacion: 4,
  // ),
  // RopaDeportiva(
  //   id: Uuid().v4(),
  //   imagen: 'assets/images/chaleco_running.jpg',
  //   titulo: 'Chaleco Running',
  //   descripcion:
  //       'Chaleco ligero y reflectante para correr en condiciones de poca luz.',
  //   precio: 38.99,
  //   tallas: ['S', 'M', 'L'],
  //   enOferta: true,
  //   ponderacion: 5,
  // ),
  // RopaDeportiva(
  //   id: Uuid().v4(),
  //   imagen: 'assets/images/mallas_ciclista.jpg',
  //   titulo: 'Mallas de Ciclista',
  //   descripcion: 'Mallas acolchadas para ciclismo de larga distancia.',
  //   precio: 45.99,
  //   tallas: ['S', 'M', 'L', 'XL'],
  //   enOferta: false,
  //   ponderacion: 3,
  // ),
];
